### ISSUE TITLE
Font used on the website?

### ISSUE THREAD

**Issue by fr3fou** [octref/shiki#12]
What is the font that is used in the website? (On the code blocks)

**Comment by hacknug** [comment]
Here's the CSS styles for the code blocks:

```css
pre code {
    white-space: pre-wrap;
    font-family: 'Input Mono', 'IBM Plex Mono', monospace;
    font-size: 14px;
}
```
